export default {
  REQUEST_POSTS:'REQUEST_POSTS',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  SELECT_SUBREDDIT: 'SELECT_SUBREDDIT',
  INVALIDATE_SUBREDDIT: 'INVALIDATE_SUBREDDIT',
  POSTS_BY_SUBREDDIT: 'POSTS_BY_SUBREDDIT'
}
